
use mydatabase;

create table  towns (
id int primary key,
town_name varchar(300),
province_id int
);


INSERT   towns  (id,town_name,province_id)               VALUES (1, 'SEYHAN', 1);
INSERT   towns  (id,town_name,province_id)               VALUES (2, 'CEYHAN', 1);
INSERT   towns  (id,town_name,province_id)               VALUES (3, 'FEKE', 1);
INSERT   towns  (id,town_name,province_id)               VALUES (4, 'KARAİSALI', 1);
INSERT   towns  (id,town_name,province_id)               VALUES (5, 'KARATAŞ', 1);
INSERT   towns  (id,town_name,province_id)               VALUES (6, 'KOZAN', 1);
INSERT   towns  (id,town_name,province_id)               VALUES (7, 'POZANTI', 1);
INSERT   towns  (id,town_name,province_id)               VALUES (8, 'SAİMBEYLİ', 1);
INSERT   towns  (id,town_name,province_id)               VALUES (9, 'TUFANBEYLİ', 1);
INSERT   towns  (id,town_name,province_id)               VALUES (10, 'YUMURTALIK', 1);
INSERT   towns  (id,town_name,province_id)               VALUES (11, 'YÜREĞİR', 1);
INSERT   towns  (id,town_name,province_id)               VALUES (12, 'ALADAĞ', 1);
INSERT   towns  (id,town_name,province_id)               VALUES (13, 'İMAMOĞLU', 1);
INSERT   towns  (id,town_name,province_id)               VALUES (14, 'ADIYAMAN MERKEZ', 2);
INSERT   towns  (id,town_name,province_id)               VALUES (15, 'BESNİ', 2);
INSERT   towns  (id,town_name,province_id)               VALUES (16, 'ÇELİKHAN', 2);
INSERT   towns  (id,town_name,province_id)               VALUES (17, 'GERGER', 2);
INSERT   towns  (id,town_name,province_id)               VALUES (18, 'GÖLBAŞI', 2);
INSERT   towns  (id,town_name,province_id)               VALUES (19, 'KAHTA', 2);
INSERT   towns  (id,town_name,province_id)               VALUES (20, 'SAMSAT', 2);
INSERT   towns  (id,town_name,province_id)               VALUES (21, 'SİNCİK', 2);
INSERT   towns  (id,town_name,province_id)               VALUES (22, 'TUT', 2);
INSERT   towns  (id,town_name,province_id)               VALUES (23, 'AFYONMERKEZ', 3);
INSERT   towns  (id,town_name,province_id)               VALUES (24, 'BOLVADİN', 3);
INSERT   towns  (id,town_name,province_id)               VALUES (25, 'ÇAY', 3);
INSERT   towns  (id,town_name,province_id)               VALUES (26, 'DAZKIRI', 3);
INSERT   towns  (id,town_name,province_id)               VALUES (27, 'DİNAR', 3);
INSERT   towns  (id,town_name,province_id)               VALUES (28, 'EMİRDAĞ', 3);
INSERT   towns  (id,town_name,province_id)               VALUES (29, 'İHSANİYE', 3);
INSERT   towns  (id,town_name,province_id)               VALUES (30, 'SANDIKLI', 3);
INSERT   towns  (id,town_name,province_id)               VALUES (31, 'SİNANPAŞA', 3);
INSERT   towns  (id,town_name,province_id)               VALUES (32, 'SULDANDAĞI', 3);
INSERT   towns  (id,town_name,province_id)               VALUES (33, 'ŞUHUT', 3);
INSERT   towns  (id,town_name,province_id)               VALUES (34, 'BAŞMAKÇI', 3);
INSERT   towns  (id,town_name,province_id)               VALUES (35, 'BAYAT', 3);
INSERT   towns  (id,town_name,province_id)               VALUES (36, 'İŞCEHİSAR', 3);
INSERT   towns  (id,town_name,province_id)               VALUES (37, 'ÇOBANLAR', 3);
INSERT   towns  (id,town_name,province_id)               VALUES (38, 'EVCİLER', 3);
INSERT   towns  (id,town_name,province_id)               VALUES (39, 'HOCALAR', 3);
INSERT   towns  (id,town_name,province_id)               VALUES (40, 'KIZILÖREN', 3);
INSERT   towns  (id,town_name,province_id)               VALUES (41, 'AKSARAY MERKEZ', 68);
INSERT   towns  (id,town_name,province_id)               VALUES (42, 'ORTAKÖY', 68);
INSERT   towns  (id,town_name,province_id)               VALUES (43, 'AĞAÇÖREN', 68);
INSERT   towns  (id,town_name,province_id)               VALUES (44, 'GÜZELYURT', 68);
INSERT   towns  (id,town_name,province_id)               VALUES (45, 'SARIYAHŞİ', 68);
INSERT   towns  (id,town_name,province_id)               VALUES (46, 'ESKİL', 68);
INSERT   towns  (id,town_name,province_id)               VALUES (47, 'GÜLAĞAÇ', 68);
INSERT   towns  (id,town_name,province_id)               VALUES (48, 'AMASYA MERKEZ', 5);
INSERT   towns  (id,town_name,province_id)               VALUES (49, 'GÖYNÜÇEK', 5);
INSERT   towns  (id,town_name,province_id)               VALUES (50, 'GÜMÜŞHACIKÖYÜ', 5);
INSERT   towns  (id,town_name,province_id)               VALUES (51, 'MERZİFON', 5);
INSERT   towns  (id,town_name,province_id)               VALUES (52, 'SULUOVA', 5);
INSERT   towns  (id,town_name,province_id)               VALUES (53, 'TAŞOVA', 5);
INSERT   towns  (id,town_name,province_id)               VALUES (54, 'HAMAMÖZÜ', 5);
INSERT   towns  (id,town_name,province_id)               VALUES (55, 'ALTINDAĞ', 6);
INSERT   towns  (id,town_name,province_id)               VALUES (56, 'AYAS', 6);
INSERT   towns  (id,town_name,province_id)               VALUES (57, 'BALA', 6);
INSERT   towns  (id,town_name,province_id)               VALUES (58, 'BEYPAZARI', 6);
INSERT   towns  (id,town_name,province_id)               VALUES (59, 'ÇAMLIDERE', 6);
INSERT   towns  (id,town_name,province_id)               VALUES (60, 'ÇANKAYA', 6);
INSERT   towns  (id,town_name,province_id)               VALUES (61, 'ÇUBUK', 6);
INSERT   towns  (id,town_name,province_id)               VALUES (62, 'ELMADAĞ', 6);
INSERT   towns  (id,town_name,province_id)               VALUES (63, 'GÜDÜL', 6);
INSERT   towns  (id,town_name,province_id)               VALUES (64, 'HAYMANA', 6);
INSERT   towns  (id,town_name,province_id)               VALUES (65, 'KALECİK', 6);
INSERT   towns  (id,town_name,province_id)               VALUES (66, 'KIZILCAHAMAM', 6);
INSERT   towns  (id,town_name,province_id)               VALUES (67, 'NALLIHAN', 6);
INSERT   towns  (id,town_name,province_id)               VALUES (68, 'POLATLI', 6);
INSERT   towns  (id,town_name,province_id)               VALUES (69, 'ŞEREFLİKOÇHİSAR', 6);
INSERT   towns  (id,town_name,province_id)               VALUES (70, 'YENİMAHALLE', 6);
INSERT   towns  (id,town_name,province_id)               VALUES (71, 'GÖLBAŞI', 6);
INSERT   towns  (id,town_name,province_id)               VALUES (72, 'KEÇİÖREN', 6);
INSERT   towns  (id,town_name,province_id)               VALUES (73, 'MAMAK', 6);
INSERT   towns  (id,town_name,province_id)               VALUES (74, 'SİNCAN', 6);
INSERT   towns  (id,town_name,province_id)               VALUES (75, 'KAZAN', 6);
INSERT   towns  (id,town_name,province_id)               VALUES (76, 'AKYURT', 6);
INSERT   towns  (id,town_name,province_id)               VALUES (77, 'ETİMESGUT', 6);
INSERT   towns  (id,town_name,province_id)               VALUES (78, 'EVREN', 6);
INSERT   towns  (id,town_name,province_id)               VALUES (79, 'ANSEKİ', 7);
INSERT   towns  (id,town_name,province_id)               VALUES (80, 'ALANYA', 7);
INSERT   towns  (id,town_name,province_id)               VALUES (81, 'ANTALYA MERKEZİ', 7);
INSERT   towns  (id,town_name,province_id)               VALUES (82, 'ELMALI', 7);
INSERT   towns  (id,town_name,province_id)               VALUES (83, 'FİNİKE', 7);
INSERT   towns  (id,town_name,province_id)               VALUES (84, 'GAZİPAŞA', 7);
INSERT   towns  (id,town_name,province_id)               VALUES (85, 'GÜNDOĞMUŞ', 7);
INSERT   towns  (id,town_name,province_id)               VALUES (86, 'KAŞ', 7);
INSERT   towns  (id,town_name,province_id)               VALUES (87, 'KORKUTELİ', 7);
INSERT   towns  (id,town_name,province_id)               VALUES (88, 'KUMLUCA', 7);
INSERT   towns  (id,town_name,province_id)               VALUES (89, 'MANAVGAT', 7);
INSERT   towns  (id,town_name,province_id)               VALUES (90, 'SERİK', 7);
INSERT   towns  (id,town_name,province_id)               VALUES (91, 'DEMRE', 7);
INSERT   towns  (id,town_name,province_id)               VALUES (92, 'İBRADI', 7);
INSERT   towns  (id,town_name,province_id)               VALUES (93, 'KEMER', 7);
INSERT   towns  (id,town_name,province_id)               VALUES (94, 'ARDAHAN MERKEZ', 75);
INSERT   towns  (id,town_name,province_id)               VALUES (95, 'GÖLE', 75);
INSERT   towns  (id,town_name,province_id)               VALUES (96, 'ÇILDIR', 75);
INSERT   towns  (id,town_name,province_id)               VALUES (97, 'HANAK', 75);
INSERT   towns  (id,town_name,province_id)               VALUES (98, 'POSOF', 75);
INSERT   towns  (id,town_name,province_id)               VALUES (99, 'DAMAL', 75);
INSERT   towns  (id,town_name,province_id)               VALUES (100, 'ARDANUÇ', 8);
INSERT   towns  (id,town_name,province_id)               VALUES (101, 'ARHAVİ', 8);
INSERT   towns  (id,town_name,province_id)               VALUES (102, 'ARTVİN MERKEZ', 8);
INSERT   towns  (id,town_name,province_id)               VALUES (103, 'BORÇKA', 8);
INSERT   towns  (id,town_name,province_id)               VALUES (104, 'HOPA', 8);
INSERT   towns  (id,town_name,province_id)               VALUES (105, 'ŞAVŞAT', 8);
INSERT   towns  (id,town_name,province_id)               VALUES (106, 'YUSUFELİ', 8);
INSERT   towns  (id,town_name,province_id)               VALUES (107, 'MURGUL', 8);
INSERT   towns  (id,town_name,province_id)               VALUES (108, 'AYDIN MERKEZ', 9);
INSERT   towns  (id,town_name,province_id)               VALUES (109, 'BOZDOĞAN', 9);
INSERT   towns  (id,town_name,province_id)               VALUES (110, 'ÇİNE', 9);
INSERT   towns  (id,town_name,province_id)               VALUES (111, 'GERMENCİK', 9);
INSERT   towns  (id,town_name,province_id)               VALUES (112, 'KARACASU', 9);
INSERT   towns  (id,town_name,province_id)               VALUES (113, 'KOÇARLI', 9);
INSERT   towns  (id,town_name,province_id)               VALUES (114, 'KUŞADASI', 9);
INSERT   towns  (id,town_name,province_id)               VALUES (115, 'KUYUCAK', 9);
INSERT   towns  (id,town_name,province_id)               VALUES (116, 'NAZİLLİ', 9);
INSERT   towns  (id,town_name,province_id)               VALUES (117, 'SÖKE', 9);
INSERT   towns  (id,town_name,province_id)               VALUES (118, 'SULTANHİSAR', 9);
INSERT   towns  (id,town_name,province_id)               VALUES (119, 'YENİPAZAR', 9);
INSERT   towns  (id,town_name,province_id)               VALUES (120, 'BUHARKENT', 9);
INSERT   towns  (id,town_name,province_id)               VALUES (121, 'İNCİRLİOVA', 9);
INSERT   towns  (id,town_name,province_id)               VALUES (122, 'KARPUZLU', 9);
INSERT   towns  (id,town_name,province_id)               VALUES (123, 'KÖŞK', 9);
INSERT   towns  (id,town_name,province_id)               VALUES (124, 'DİDİM', 9);
INSERT   towns  (id,town_name,province_id)               VALUES (125, 'AĞRI MERKEZ', 4);
INSERT   towns  (id,town_name,province_id)               VALUES (126, 'DİYADİN', 4);
INSERT   towns  (id,town_name,province_id)               VALUES (127, 'DOĞUBEYAZIT', 4);
INSERT   towns  (id,town_name,province_id)               VALUES (128, 'ELEŞKİRT', 4);
INSERT   towns  (id,town_name,province_id)               VALUES (129, 'HAMUR', 4);
INSERT   towns  (id,town_name,province_id)               VALUES (130, 'PATNOS', 4);
INSERT   towns  (id,town_name,province_id)               VALUES (131, 'TAŞLIÇAY', 4);
INSERT   towns  (id,town_name,province_id)               VALUES (132, 'TUTAK', 4);
INSERT   towns  (id,town_name,province_id)               VALUES (133, 'AYVALIK', 10);
INSERT   towns  (id,town_name,province_id)               VALUES (134, 'BALIKESİR MERKEZ', 10);
INSERT   towns  (id,town_name,province_id)               VALUES (135, 'BALYA', 10);
INSERT   towns  (id,town_name,province_id)               VALUES (136, 'BANDIRMA', 10);
INSERT   towns  (id,town_name,province_id)               VALUES (137, 'BİGADİÇ', 10);
INSERT   towns  (id,town_name,province_id)               VALUES (138, 'BURHANİYE', 10);
INSERT   towns  (id,town_name,province_id)               VALUES (139, 'DURSUNBEY', 10);
INSERT   towns  (id,town_name,province_id)               VALUES (140, 'EDREMİT', 10);
INSERT   towns  (id,town_name,province_id)               VALUES (141, 'ERDEK', 10);
INSERT   towns  (id,town_name,province_id)               VALUES (142, 'GÖNEN', 10);
INSERT   towns  (id,town_name,province_id)               VALUES (143, 'HAVRAN', 10);
INSERT   towns  (id,town_name,province_id)               VALUES (144, 'İVRİNDİ', 10);
INSERT   towns  (id,town_name,province_id)               VALUES (145, 'KEPSUT', 10);
INSERT   towns  (id,town_name,province_id)               VALUES (146, 'MANYAS', 10);
INSERT   towns  (id,town_name,province_id)               VALUES (147, 'SAVAŞTEPE', 10);
INSERT   towns  (id,town_name,province_id)               VALUES (148, 'SINDIRGI', 10);
INSERT   towns  (id,town_name,province_id)               VALUES (149, 'SUSURLUK', 10);
INSERT   towns  (id,town_name,province_id)               VALUES (150, 'MARMARA', 10);
INSERT   towns  (id,town_name,province_id)               VALUES (151, 'GÖMEÇ', 10);
INSERT   towns  (id,town_name,province_id)               VALUES (152, 'BARTIN MERKEZ', 74);
INSERT   towns  (id,town_name,province_id)               VALUES (153, 'KURUCAŞİLE', 74);
INSERT   towns  (id,town_name,province_id)               VALUES (154, 'ULUS', 74);
INSERT   towns  (id,town_name,province_id)               VALUES (155, 'AMASRA', 74);
INSERT   towns  (id,town_name,province_id)               VALUES (156, 'BATMAN MERKEZ', 72);
INSERT   towns  (id,town_name,province_id)               VALUES (157, 'BEŞİRİ', 72);
INSERT   towns  (id,town_name,province_id)               VALUES (158, 'GERCÜŞ', 72);
INSERT   towns  (id,town_name,province_id)               VALUES (159, 'KOZLUK', 72);
INSERT   towns  (id,town_name,province_id)               VALUES (160, 'SASON', 72);
INSERT   towns  (id,town_name,province_id)               VALUES (161, 'HASANKEYF', 72);
INSERT   towns  (id,town_name,province_id)               VALUES (162, 'BAYBURT MERKEZ', 69);
INSERT   towns  (id,town_name,province_id)               VALUES (163, 'AYDINTEPE', 69);
INSERT   towns  (id,town_name,province_id)               VALUES (164, 'DEMİRÖZÜ', 69);
INSERT   towns  (id,town_name,province_id)               VALUES (165, 'BOLU MERKEZ', 14);
INSERT   towns  (id,town_name,province_id)               VALUES (166, 'GEREDE', 14);
INSERT   towns  (id,town_name,province_id)               VALUES (167, 'GÖYNÜK', 14);
INSERT   towns  (id,town_name,province_id)               VALUES (168, 'KIBRISCIK', 14);
INSERT   towns  (id,town_name,province_id)               VALUES (169, 'MENGEN', 14);
INSERT   towns  (id,town_name,province_id)               VALUES (170, 'MUDURNU', 14);
INSERT   towns  (id,town_name,province_id)               VALUES (171, 'SEBEN', 14);
INSERT   towns  (id,town_name,province_id)               VALUES (172, 'DÖRTDİVAN', 14);
INSERT   towns  (id,town_name,province_id)               VALUES (173, 'YENİÇAĞA', 14);
INSERT   towns  (id,town_name,province_id)               VALUES (174, 'AĞLASUN', 15);
INSERT   towns  (id,town_name,province_id)               VALUES (175, 'BUCAK', 15);
INSERT   towns  (id,town_name,province_id)               VALUES (176, 'BURDUR MERKEZ', 15);
INSERT   towns  (id,town_name,province_id)               VALUES (177, 'GÖLHİSAR', 15);
INSERT   towns  (id,town_name,province_id)               VALUES (178, 'TEFENNİ', 15);
INSERT   towns  (id,town_name,province_id)               VALUES (179, 'YEŞİLOVA', 15);
INSERT   towns  (id,town_name,province_id)               VALUES (180, 'KARAMANLI', 15);
INSERT   towns  (id,town_name,province_id)               VALUES (181, 'KEMER', 15);
INSERT   towns  (id,town_name,province_id)               VALUES (182, 'ALTINYAYLA', 15);
INSERT   towns  (id,town_name,province_id)               VALUES (183, 'ÇAVDIR', 15);
INSERT   towns  (id,town_name,province_id)               VALUES (184, 'ÇELTİKÇİ', 15);
INSERT   towns  (id,town_name,province_id)               VALUES (185, 'GEMLİK', 16);
INSERT   towns  (id,town_name,province_id)               VALUES (186, 'İNEGÖL', 16);
INSERT   towns  (id,town_name,province_id)               VALUES (187, 'İZNİK', 16);
INSERT   towns  (id,town_name,province_id)               VALUES (188, 'KARACABEY', 16);
INSERT   towns  (id,town_name,province_id)               VALUES (189, 'KELES', 16);
INSERT   towns  (id,town_name,province_id)               VALUES (190, 'MUDANYA', 16);
INSERT   towns  (id,town_name,province_id)               VALUES (191, 'MUSTAFA K. PAŞA', 16);
INSERT   towns  (id,town_name,province_id)               VALUES (192, 'ORHANELİ', 16);
INSERT   towns  (id,town_name,province_id)               VALUES (193, 'ORHANGAZİ', 16);
INSERT   towns  (id,town_name,province_id)               VALUES (194, 'YENİŞEHİR', 16);
INSERT   towns  (id,town_name,province_id)               VALUES (195, 'BÜYÜK ORHAN', 16);
INSERT   towns  (id,town_name,province_id)               VALUES (196, 'HARMANCIK', 16);
INSERT   towns  (id,town_name,province_id)               VALUES (197, 'NÜLİFER', 16);
INSERT   towns  (id,town_name,province_id)               VALUES (198, 'OSMAN GAZİ', 16);
INSERT   towns  (id,town_name,province_id)               VALUES (199, 'YILDIRIM', 16);
INSERT   towns  (id,town_name,province_id)               VALUES (200, 'GÜRSU', 16);
INSERT   towns  (id,town_name,province_id)               VALUES (201, 'KESTEL', 16);
INSERT   towns  (id,town_name,province_id)               VALUES (202, 'BİLECİK MERKEZ', 11);
INSERT   towns  (id,town_name,province_id)               VALUES (203, 'BOZÜYÜK', 11);
INSERT   towns  (id,town_name,province_id)               VALUES (204, 'GÖLPAZARI', 11);
INSERT   towns  (id,town_name,province_id)               VALUES (205, 'OSMANELİ', 11);
INSERT   towns  (id,town_name,province_id)               VALUES (206, 'PAZARYERİ', 11);
INSERT   towns  (id,town_name,province_id)               VALUES (207, 'SÖĞÜT', 11);
INSERT   towns  (id,town_name,province_id)               VALUES (208, 'YENİPAZAR', 11);
INSERT   towns  (id,town_name,province_id)               VALUES (209, 'İNHİSAR', 11);
INSERT   towns  (id,town_name,province_id)               VALUES (210, 'BİNGÖL MERKEZ', 12);
INSERT   towns  (id,town_name,province_id)               VALUES (211, 'GENÇ', 12);
INSERT   towns  (id,town_name,province_id)               VALUES (212, 'KARLIOVA', 12);
INSERT   towns  (id,town_name,province_id)               VALUES (213, 'KİGI', 12);
INSERT   towns  (id,town_name,province_id)               VALUES (214, 'SOLHAN', 12);
INSERT   towns  (id,town_name,province_id)               VALUES (215, 'ADAKLI', 12);
INSERT   towns  (id,town_name,province_id)               VALUES (216, 'YAYLADERE', 12);
INSERT   towns  (id,town_name,province_id)               VALUES (217, 'YEDİSU', 12);
INSERT   towns  (id,town_name,province_id)               VALUES (218, 'ADİLCEVAZ', 13);
INSERT   towns  (id,town_name,province_id)               VALUES (219, 'AHLAT', 13);
INSERT   towns  (id,town_name,province_id)               VALUES (220, 'BİTLİS MERKEZ', 13);
INSERT   towns  (id,town_name,province_id)               VALUES (221, 'HİZAN', 13);
INSERT   towns  (id,town_name,province_id)               VALUES (222, 'MUTKİ', 13);
INSERT   towns  (id,town_name,province_id)               VALUES (223, 'TATVAN', 13);
INSERT   towns  (id,town_name,province_id)               VALUES (224, 'GÜROYMAK', 13);
INSERT   towns  (id,town_name,province_id)               VALUES (225, 'DENİZLİ MERKEZ', 20);
INSERT   towns  (id,town_name,province_id)               VALUES (226, 'ACIPAYAM', 20);
INSERT   towns  (id,town_name,province_id)               VALUES (227, 'BULDAN', 20);
INSERT   towns  (id,town_name,province_id)               VALUES (228, 'ÇAL', 20);
INSERT   towns  (id,town_name,province_id)               VALUES (229, 'ÇAMELİ', 20);
INSERT   towns  (id,town_name,province_id)               VALUES (230, 'ÇARDAK', 20);
INSERT   towns  (id,town_name,province_id)               VALUES (231, 'ÇİVRİL', 20);
INSERT   towns  (id,town_name,province_id)               VALUES (232, 'GÜNEY', 20);
INSERT   towns  (id,town_name,province_id)               VALUES (233, 'KALE', 20);
INSERT   towns  (id,town_name,province_id)               VALUES (234, 'SARAYKÖY', 20);
INSERT   towns  (id,town_name,province_id)               VALUES (235, 'TAVAS', 20);
INSERT   towns  (id,town_name,province_id)               VALUES (236, 'BABADAĞ', 20);
INSERT   towns  (id,town_name,province_id)               VALUES (237, 'BEKİLLİ', 20);
INSERT   towns  (id,town_name,province_id)               VALUES (238, 'HONAZ', 20);
INSERT   towns  (id,town_name,province_id)               VALUES (239, 'SERİNHİSAR', 20);
INSERT   towns  (id,town_name,province_id)               VALUES (240, 'AKKÖY', 20);
INSERT   towns  (id,town_name,province_id)               VALUES (241, 'BAKLAN', 20);
INSERT   towns  (id,town_name,province_id)               VALUES (242, 'BEYAĞAÇ', 20);
INSERT   towns  (id,town_name,province_id)               VALUES (243, 'BOZKURT', 20);
INSERT   towns  (id,town_name,province_id)               VALUES (244, 'DÜZCE MERKEZ', 81);
INSERT   towns  (id,town_name,province_id)               VALUES (245, 'AKÇAKOCA', 81);
INSERT   towns  (id,town_name,province_id)               VALUES (246, 'YIĞILCA', 81);
INSERT   towns  (id,town_name,province_id)               VALUES (247, 'CUMAYERİ', 81);
INSERT   towns  (id,town_name,province_id)               VALUES (248, 'GÖLYAKA', 81);
INSERT   towns  (id,town_name,province_id)               VALUES (249, 'ÇİLİMLİ', 81);
INSERT   towns  (id,town_name,province_id)               VALUES (250, 'GÜMÜŞOVA', 81);
INSERT   towns  (id,town_name,province_id)               VALUES (251, 'KAYNAŞLI', 81);
INSERT   towns  (id,town_name,province_id)               VALUES (252, 'DİYARBAKIR MERKEZ', 21);
INSERT   towns  (id,town_name,province_id)               VALUES (253, 'BİSMİL', 21);
INSERT   towns  (id,town_name,province_id)               VALUES (254, 'ÇERMİK', 21);
INSERT   towns  (id,town_name,province_id)               VALUES (255, 'ÇINAR', 21);
INSERT   towns  (id,town_name,province_id)               VALUES (256, 'ÇÜNGÜŞ', 21);
INSERT   towns  (id,town_name,province_id)               VALUES (257, 'DİCLE', 21);
INSERT   towns  (id,town_name,province_id)               VALUES (258, 'ERGANİ', 21);
INSERT   towns  (id,town_name,province_id)               VALUES (259, 'HANİ', 21);
INSERT   towns  (id,town_name,province_id)               VALUES (260, 'HAZRO', 21);
INSERT   towns  (id,town_name,province_id)               VALUES (261, 'KULP', 21);
INSERT   towns  (id,town_name,province_id)               VALUES (262, 'LİCE', 21);
INSERT   towns  (id,town_name,province_id)               VALUES (263, 'SİLVAN', 21);
INSERT   towns  (id,town_name,province_id)               VALUES (264, 'EĞİL', 21);
INSERT   towns  (id,town_name,province_id)               VALUES (265, 'KOCAKÖY', 21);
INSERT   towns  (id,town_name,province_id)               VALUES (266, 'EDİRNE MERKEZ', 22);
INSERT   towns  (id,town_name,province_id)               VALUES (267, 'ENEZ', 22);
INSERT   towns  (id,town_name,province_id)               VALUES (268, 'HAVSA', 22);
INSERT   towns  (id,town_name,province_id)               VALUES (269, 'İPSALA', 22);
INSERT   towns  (id,town_name,province_id)               VALUES (270, 'KEŞAN', 22);
INSERT   towns  (id,town_name,province_id)               VALUES (271, 'LALAPAŞA', 22);
INSERT   towns  (id,town_name,province_id)               VALUES (272, 'MERİÇ', 22);
INSERT   towns  (id,town_name,province_id)               VALUES (273, 'UZUNKÖPRÜ', 22);
INSERT   towns  (id,town_name,province_id)               VALUES (274, 'SÜLOĞLU', 22);
INSERT   towns  (id,town_name,province_id)               VALUES (275, 'ELAZIĞ MERKEZ', 23);
INSERT   towns  (id,town_name,province_id)               VALUES (276, 'AĞIN', 23);
INSERT   towns  (id,town_name,province_id)               VALUES (277, 'BASKİL', 23);
INSERT   towns  (id,town_name,province_id)               VALUES (278, 'KARAKOÇAN', 23);
INSERT   towns  (id,town_name,province_id)               VALUES (279, 'KEBAN', 23);
INSERT   towns  (id,town_name,province_id)               VALUES (280, 'MADEN', 23);
INSERT   towns  (id,town_name,province_id)               VALUES (281, 'PALU', 23);
INSERT   towns  (id,town_name,province_id)               VALUES (282, 'SİVRİCE', 23);
INSERT   towns  (id,town_name,province_id)               VALUES (283, 'ARICAK', 23);
INSERT   towns  (id,town_name,province_id)               VALUES (284, 'KOVANCILAR', 23);
INSERT   towns  (id,town_name,province_id)               VALUES (285, 'ALACAKAYA', 23);
INSERT   towns  (id,town_name,province_id)               VALUES (286, 'ERZURUM MERKEZ', 25);
INSERT   towns  (id,town_name,province_id)               VALUES (287, 'PALANDÖKEN', 25);
INSERT   towns  (id,town_name,province_id)               VALUES (288, 'AŞKALE', 25);
INSERT   towns  (id,town_name,province_id)               VALUES (289, 'ÇAT', 25);
INSERT   towns  (id,town_name,province_id)               VALUES (290, 'HINIS', 25);
INSERT   towns  (id,town_name,province_id)               VALUES (291, 'HORASAN', 25);
INSERT   towns  (id,town_name,province_id)               VALUES (292, 'OLTU', 25);
INSERT   towns  (id,town_name,province_id)               VALUES (293, 'İSPİR', 25);
INSERT   towns  (id,town_name,province_id)               VALUES (294, 'KARAYAZI', 25);
INSERT   towns  (id,town_name,province_id)               VALUES (295, 'NARMAN', 25);
INSERT   towns  (id,town_name,province_id)               VALUES (296, 'OLUR', 25);
INSERT   towns  (id,town_name,province_id)               VALUES (297, 'PASİNLER', 25);
INSERT   towns  (id,town_name,province_id)               VALUES (298, 'ŞENKAYA', 25);
INSERT   towns  (id,town_name,province_id)               VALUES (299, 'TEKMAN', 25);
INSERT   towns  (id,town_name,province_id)               VALUES (300, 'TORTUM', 25);
INSERT   towns  (id,town_name,province_id)               VALUES (301, 'KARAÇOBAN', 25);
INSERT   towns  (id,town_name,province_id)               VALUES (302, 'UZUNDERE', 25);
INSERT   towns  (id,town_name,province_id)               VALUES (303, 'PAZARYOLU', 25);
INSERT   towns  (id,town_name,province_id)               VALUES (304, 'ILICA', 25);
INSERT   towns  (id,town_name,province_id)               VALUES (305, 'KÖPRÜKÖY', 25);
INSERT   towns  (id,town_name,province_id)               VALUES (306, 'ÇAYIRLI', 24);
INSERT   towns  (id,town_name,province_id)               VALUES (307, 'ERZİNCAN MERKEZ', 24);
INSERT   towns  (id,town_name,province_id)               VALUES (308, 'İLİÇ', 24);
INSERT   towns  (id,town_name,province_id)               VALUES (309, 'KEMAH', 24);
INSERT   towns  (id,town_name,province_id)               VALUES (310, 'KEMALİYE', 24);
INSERT   towns  (id,town_name,province_id)               VALUES (311, 'REFAHİYE', 24);
INSERT   towns  (id,town_name,province_id)               VALUES (312, 'TERCAN', 24);
INSERT   towns  (id,town_name,province_id)               VALUES (313, 'OTLUKBELİ', 24);
INSERT   towns  (id,town_name,province_id)               VALUES (314, 'ESKİŞEHİR MERKEZ', 26);
INSERT   towns  (id,town_name,province_id)               VALUES (315, 'ÇİFTELER', 26);
INSERT   towns  (id,town_name,province_id)               VALUES (316, 'MAHMUDİYE', 26);
INSERT   towns  (id,town_name,province_id)               VALUES (317, 'MİHALIÇLIK', 26);
INSERT   towns  (id,town_name,province_id)               VALUES (318, 'SARICAKAYA', 26);
INSERT   towns  (id,town_name,province_id)               VALUES (319, 'SEYİTGAZİ', 26);
INSERT   towns  (id,town_name,province_id)               VALUES (320, 'SİVRİHİSAR', 26);
INSERT   towns  (id,town_name,province_id)               VALUES (321, 'ALPU', 26);
INSERT   towns  (id,town_name,province_id)               VALUES (322, 'BEYLİKOVA', 26);
INSERT   towns  (id,town_name,province_id)               VALUES (323, 'İNÖNÜ', 26);
INSERT   towns  (id,town_name,province_id)               VALUES (324, 'GÜNYÜZÜ', 26);
INSERT   towns  (id,town_name,province_id)               VALUES (325, 'HAN', 26);
INSERT   towns  (id,town_name,province_id)               VALUES (326, 'MİHALGAZİ', 26);
INSERT   towns  (id,town_name,province_id)               VALUES (327, 'ARABAN', 27);
INSERT   towns  (id,town_name,province_id)               VALUES (328, 'İSLAHİYE', 27);
INSERT   towns  (id,town_name,province_id)               VALUES (329, 'NİZİP', 27);
INSERT   towns  (id,town_name,province_id)               VALUES (330, 'OĞUZELİ', 27);
INSERT   towns  (id,town_name,province_id)               VALUES (331, 'YAVUZELİ', 27);
INSERT   towns  (id,town_name,province_id)               VALUES (332, 'ŞAHİNBEY', 27);
INSERT   towns  (id,town_name,province_id)               VALUES (333, 'ŞEHİT KAMİL', 27);
INSERT   towns  (id,town_name,province_id)               VALUES (334, 'KARKAMIŞ', 27);
INSERT   towns  (id,town_name,province_id)               VALUES (335, 'NURDAĞI', 27);
INSERT   towns  (id,town_name,province_id)               VALUES (336, 'GÜMÜŞHANE MERKEZ', 29);
INSERT   towns  (id,town_name,province_id)               VALUES (337, 'KELKİT', 29);
INSERT   towns  (id,town_name,province_id)               VALUES (338, 'ŞİRAN', 29);
INSERT   towns  (id,town_name,province_id)               VALUES (339, 'TORUL', 29);
INSERT   towns  (id,town_name,province_id)               VALUES (340, 'KÖSE', 29);
INSERT   towns  (id,town_name,province_id)               VALUES (341, 'KÜRTÜN', 29);
INSERT   towns  (id,town_name,province_id)               VALUES (342, 'ALUCRA', 28);
INSERT   towns  (id,town_name,province_id)               VALUES (343, 'BULANCAK', 28);
INSERT   towns  (id,town_name,province_id)               VALUES (344, 'DERELİ', 28);
INSERT   towns  (id,town_name,province_id)               VALUES (345, 'ESPİYE', 28);
INSERT   towns  (id,town_name,province_id)               VALUES (346, 'EYNESİL', 28);
INSERT   towns  (id,town_name,province_id)               VALUES (347, 'GİRESUN MERKEZ', 28);
INSERT   towns  (id,town_name,province_id)               VALUES (348, 'GÖRELE', 28);
INSERT   towns  (id,town_name,province_id)               VALUES (349, 'KEŞAP', 28);
INSERT   towns  (id,town_name,province_id)               VALUES (350, 'ŞEBİNKARAHİSAR', 28);
INSERT   towns  (id,town_name,province_id)               VALUES (351, 'TİREBOLU', 28);
INSERT   towns  (id,town_name,province_id)               VALUES (352, 'PİPAZİZ', 28);
INSERT   towns  (id,town_name,province_id)               VALUES (353, 'YAĞLIDERE', 28);
INSERT   towns  (id,town_name,province_id)               VALUES (354, 'ÇAMOLUK', 28);
INSERT   towns  (id,town_name,province_id)               VALUES (355, 'ÇANAKÇI', 28);
INSERT   towns  (id,town_name,province_id)               VALUES (356, 'DOĞANKENT', 28);
INSERT   towns  (id,town_name,province_id)               VALUES (357, 'GÜCE', 28);
INSERT   towns  (id,town_name,province_id)               VALUES (358, 'HAKKARİ MERKEZ', 30);
INSERT   towns  (id,town_name,province_id)               VALUES (359, 'ÇUKURCA', 30);
INSERT   towns  (id,town_name,province_id)               VALUES (360, 'ŞEMDİNLİ', 30);
INSERT   towns  (id,town_name,province_id)               VALUES (361, 'YÜKSEKOVA', 30);
INSERT   towns  (id,town_name,province_id)               VALUES (362, 'ALTINÖZÜ', 31);
INSERT   towns  (id,town_name,province_id)               VALUES (363, 'DÖRTYOL', 31);
INSERT   towns  (id,town_name,province_id)               VALUES (364, 'HATAY MERKEZ', 31);
INSERT   towns  (id,town_name,province_id)               VALUES (365, 'HASSA', 31);
INSERT   towns  (id,town_name,province_id)               VALUES (366, 'İSKENDERUN', 31);
INSERT   towns  (id,town_name,province_id)               VALUES (367, 'KIRIKHAN', 31);
INSERT   towns  (id,town_name,province_id)               VALUES (368, 'REYHANLI', 31);
INSERT   towns  (id,town_name,province_id)               VALUES (369, 'SAMANDAĞ', 31);
INSERT   towns  (id,town_name,province_id)               VALUES (370, 'YAYLADAĞ', 31);
INSERT   towns  (id,town_name,province_id)               VALUES (371, 'ERZİN', 31);
INSERT   towns  (id,town_name,province_id)               VALUES (372, 'BELEN', 31);
INSERT   towns  (id,town_name,province_id)               VALUES (373, 'KUMLU', 31);
INSERT   towns  (id,town_name,province_id)               VALUES (374, 'ISPARTA MERKEZ', 32);
INSERT   towns  (id,town_name,province_id)               VALUES (375, 'ATABEY', 32);
INSERT   towns  (id,town_name,province_id)               VALUES (376, 'KEÇİBORLU', 32);
INSERT   towns  (id,town_name,province_id)               VALUES (377, 'EĞİRDİR', 32);
INSERT   towns  (id,town_name,province_id)               VALUES (378, 'GELENDOST', 32);
INSERT   towns  (id,town_name,province_id)               VALUES (379, 'SİNİRKENT', 32);
INSERT   towns  (id,town_name,province_id)               VALUES (380, 'ULUBORLU', 32);
INSERT   towns  (id,town_name,province_id)               VALUES (381, 'YALVAÇ', 32);
INSERT   towns  (id,town_name,province_id)               VALUES (382, 'AKSU', 32);
INSERT   towns  (id,town_name,province_id)               VALUES (383, 'GÖNEN', 32);
INSERT   towns  (id,town_name,province_id)               VALUES (384, 'YENİŞAR BADEMLİ', 32);
INSERT   towns  (id,town_name,province_id)               VALUES (385, 'IĞDIR MERKEZ', 76);
INSERT   towns  (id,town_name,province_id)               VALUES (386, 'ARALIK', 76);
INSERT   towns  (id,town_name,province_id)               VALUES (387, 'TUZLUCA', 76);
INSERT   towns  (id,town_name,province_id)               VALUES (388, 'KARAKOYUNLU', 76);
INSERT   towns  (id,town_name,province_id)               VALUES (389, 'AFŞİN', 46);
INSERT   towns  (id,town_name,province_id)               VALUES (390, 'ANDIRIN', 46);
INSERT   towns  (id,town_name,province_id)               VALUES (391, 'ELBİSTAN', 46);
INSERT   towns  (id,town_name,province_id)               VALUES (392, 'GÖKSUN', 46);
INSERT   towns  (id,town_name,province_id)               VALUES (393, 'KAHRAMANMARAŞ MERKEZ', 46);
INSERT   towns  (id,town_name,province_id)               VALUES (394, 'PAZARCIK', 46);
INSERT   towns  (id,town_name,province_id)               VALUES (395, 'TÜRKOĞLU', 46);
INSERT   towns  (id,town_name,province_id)               VALUES (396, 'ÇAĞLAYANCERİT', 46);
INSERT   towns  (id,town_name,province_id)               VALUES (397, 'EKİNÖZÜ', 46);
INSERT   towns  (id,town_name,province_id)               VALUES (398, 'NURHAK', 46);
INSERT   towns  (id,town_name,province_id)               VALUES (399, 'EFLANİ', 78);
INSERT   towns  (id,town_name,province_id)               VALUES (400, 'ESKİPAZAR', 78);
INSERT   towns  (id,town_name,province_id)               VALUES (401, 'KARABÜK MERKEZ', 78);
INSERT   towns  (id,town_name,province_id)               VALUES (402, 'OVACIK', 78);
INSERT   towns  (id,town_name,province_id)               VALUES (403, 'SAFRANBOLU', 78);
INSERT   towns  (id,town_name,province_id)               VALUES (404, 'YENİCE', 78);
INSERT   towns  (id,town_name,province_id)               VALUES (405, 'ERMENEK', 70);
INSERT   towns  (id,town_name,province_id)               VALUES (406, 'KARAMAN MERKEZ', 70);
INSERT   towns  (id,town_name,province_id)               VALUES (407, 'AYRANCI', 70);
INSERT   towns  (id,town_name,province_id)               VALUES (408, 'KAZIMKARABEKİR', 70);
INSERT   towns  (id,town_name,province_id)               VALUES (409, 'BAŞYAYLA', 70);
INSERT   towns  (id,town_name,province_id)               VALUES (410, 'SARIVELİLER', 70);
INSERT   towns  (id,town_name,province_id)               VALUES (411, 'KARS MERKEZ', 36);
INSERT   towns  (id,town_name,province_id)               VALUES (412, 'ARPAÇAY', 36);
INSERT   towns  (id,town_name,province_id)               VALUES (413, 'DİGOR', 36);
INSERT   towns  (id,town_name,province_id)               VALUES (414, 'KAĞIZMAN', 36);
INSERT   towns  (id,town_name,province_id)               VALUES (415, 'SARIKAMIŞ', 36);
INSERT   towns  (id,town_name,province_id)               VALUES (416, 'SELİM', 36);
INSERT   towns  (id,town_name,province_id)               VALUES (417, 'SUSUZ', 36);
INSERT   towns  (id,town_name,province_id)               VALUES (418, 'AKYAKA', 36);
INSERT   towns  (id,town_name,province_id)               VALUES (419, 'ABANA', 37);
INSERT   towns  (id,town_name,province_id)               VALUES (420, 'KASTAMONU MERKEZ', 37);
INSERT   towns  (id,town_name,province_id)               VALUES (421, 'ARAÇ', 37);
INSERT   towns  (id,town_name,province_id)               VALUES (422, 'AZDAVAY', 37);
INSERT   towns  (id,town_name,province_id)               VALUES (423, 'BOZKURT', 37);
INSERT   towns  (id,town_name,province_id)               VALUES (424, 'CİDE', 37);
INSERT   towns  (id,town_name,province_id)               VALUES (425, 'ÇATALZEYTİN', 37);
INSERT   towns  (id,town_name,province_id)               VALUES (426, 'DADAY', 37);
INSERT   towns  (id,town_name,province_id)               VALUES (427, 'DEVREKANİ', 37);
INSERT   towns  (id,town_name,province_id)               VALUES (428, 'İNEBOLU', 37);
INSERT   towns  (id,town_name,province_id)               VALUES (429, 'KÜRE', 37);
INSERT   towns  (id,town_name,province_id)               VALUES (430, 'TAŞKÖPRÜ', 37);
INSERT   towns  (id,town_name,province_id)               VALUES (431, 'TOSYA', 37);
INSERT   towns  (id,town_name,province_id)               VALUES (432, 'İHSANGAZİ', 37);
INSERT   towns  (id,town_name,province_id)               VALUES (433, 'PINARBAŞI', 37);
INSERT   towns  (id,town_name,province_id)               VALUES (434, 'ŞENPAZAR', 37);
INSERT   towns  (id,town_name,province_id)               VALUES (435, 'AĞLI', 37);
INSERT   towns  (id,town_name,province_id)               VALUES (436, 'DOĞANYURT', 37);
INSERT   towns  (id,town_name,province_id)               VALUES (437, 'HANÖNÜ', 37);
INSERT   towns  (id,town_name,province_id)               VALUES (438, 'SEYDİLER', 37);
INSERT   towns  (id,town_name,province_id)               VALUES (439, 'BÜNYAN', 38);
INSERT   towns  (id,town_name,province_id)               VALUES (440, 'DEVELİ', 38);
INSERT   towns  (id,town_name,province_id)               VALUES (441, 'FELAHİYE', 38);
INSERT   towns  (id,town_name,province_id)               VALUES (442, 'İNCESU', 38);
INSERT   towns  (id,town_name,province_id)               VALUES (443, 'PINARBAŞI', 38);
INSERT   towns  (id,town_name,province_id)               VALUES (444, 'SARIOĞLAN', 38);
INSERT   towns  (id,town_name,province_id)               VALUES (445, 'SARIZ', 38);
INSERT   towns  (id,town_name,province_id)               VALUES (446, 'TOMARZA', 38);
INSERT   towns  (id,town_name,province_id)               VALUES (447, 'YAHYALI', 38);
INSERT   towns  (id,town_name,province_id)               VALUES (448, 'YEŞİLHİSAR', 38);
INSERT   towns  (id,town_name,province_id)               VALUES (449, 'AKKIŞLA', 38);
INSERT   towns  (id,town_name,province_id)               VALUES (450, 'TALAS', 38);
INSERT   towns  (id,town_name,province_id)               VALUES (451, 'KOCASİNAN', 38);
INSERT   towns  (id,town_name,province_id)               VALUES (452, 'MELİKGAZİ', 38);
INSERT   towns  (id,town_name,province_id)               VALUES (453, 'HACILAR', 38);
INSERT   towns  (id,town_name,province_id)               VALUES (454, 'ÖZVATAN', 38);
INSERT   towns  (id,town_name,province_id)               VALUES (455, 'DERİCE', 71);
INSERT   towns  (id,town_name,province_id)               VALUES (456, 'KESKİN', 71);
INSERT   towns  (id,town_name,province_id)               VALUES (457, 'KIRIKKALE MERKEZ', 71);
INSERT   towns  (id,town_name,province_id)               VALUES (458, 'SALAK YURT', 71);
INSERT   towns  (id,town_name,province_id)               VALUES (459, 'BAHŞİLİ', 71);
INSERT   towns  (id,town_name,province_id)               VALUES (460, 'BALIŞEYH', 71);
INSERT   towns  (id,town_name,province_id)               VALUES (461, 'ÇELEBİ', 71);
INSERT   towns  (id,town_name,province_id)               VALUES (462, 'KARAKEÇİLİ', 71);
INSERT   towns  (id,town_name,province_id)               VALUES (463, 'YAHŞİHAN', 71);
INSERT   towns  (id,town_name,province_id)               VALUES (464, 'KIRKKLARELİ MERKEZ', 39);
INSERT   towns  (id,town_name,province_id)               VALUES (465, 'BABAESKİ', 39);
INSERT   towns  (id,town_name,province_id)               VALUES (466, 'DEMİRKÖY', 39);
INSERT   towns  (id,town_name,province_id)               VALUES (467, 'KOFÇAY', 39);
INSERT   towns  (id,town_name,province_id)               VALUES (468, 'LÜLEBURGAZ', 39);
INSERT   towns  (id,town_name,province_id)               VALUES (469, 'VİZE', 39);
INSERT   towns  (id,town_name,province_id)               VALUES (470, 'KIRŞEHİR MERKEZ', 40);
INSERT   towns  (id,town_name,province_id)               VALUES (471, 'ÇİÇEKDAĞI', 40);
INSERT   towns  (id,town_name,province_id)               VALUES (472, 'KAMAN', 40);
INSERT   towns  (id,town_name,province_id)               VALUES (473, 'MUCUR', 40);
INSERT   towns  (id,town_name,province_id)               VALUES (474, 'AKPINAR', 40);
INSERT   towns  (id,town_name,province_id)               VALUES (475, 'AKÇAKENT', 40);
INSERT   towns  (id,town_name,province_id)               VALUES (476, 'BOZTEPE', 40);
INSERT   towns  (id,town_name,province_id)               VALUES (477, 'KOCAELİ MERKEZ', 41);
INSERT   towns  (id,town_name,province_id)               VALUES (478, 'GEBZE', 41);
INSERT   towns  (id,town_name,province_id)               VALUES (479, 'GÖLCÜK', 41);
INSERT   towns  (id,town_name,province_id)               VALUES (480, 'KANDIRA', 41);
INSERT   towns  (id,town_name,province_id)               VALUES (481, 'KARAMÜRSEL', 41);
INSERT   towns  (id,town_name,province_id)               VALUES (482, 'KÖRFEZ', 41);
INSERT   towns  (id,town_name,province_id)               VALUES (483, 'DERİNCE', 41);
INSERT   towns  (id,town_name,province_id)               VALUES (484, 'KONYA MERKEZ', 42);
INSERT   towns  (id,town_name,province_id)               VALUES (485, 'AKŞEHİR', 42);
INSERT   towns  (id,town_name,province_id)               VALUES (486, 'BEYŞEHİR', 42);
INSERT   towns  (id,town_name,province_id)               VALUES (487, 'BOZKIR', 42);
INSERT   towns  (id,town_name,province_id)               VALUES (488, 'CİHANBEYLİ', 42);
INSERT   towns  (id,town_name,province_id)               VALUES (489, 'ÇUMRA', 42);
INSERT   towns  (id,town_name,province_id)               VALUES (490, 'DOĞANHİSAR', 42);
INSERT   towns  (id,town_name,province_id)               VALUES (491, 'EREĞLİ', 42);
INSERT   towns  (id,town_name,province_id)               VALUES (492, 'HADİM', 42);
INSERT   towns  (id,town_name,province_id)               VALUES (493, 'ILGIN', 42);
INSERT   towns  (id,town_name,province_id)               VALUES (494, 'KADINHANI', 42);
INSERT   towns  (id,town_name,province_id)               VALUES (495, 'KARAPINAR', 42);
INSERT   towns  (id,town_name,province_id)               VALUES (496, 'KULU', 42);
INSERT   towns  (id,town_name,province_id)               VALUES (497, 'SARAYÖNÜ', 42);
INSERT   towns  (id,town_name,province_id)               VALUES (498, 'SEYDİŞEHİR', 42);
INSERT   towns  (id,town_name,province_id)               VALUES (499, 'YUNAK', 42);
INSERT   towns  (id,town_name,province_id)               VALUES (500, 'AKÖREN', 42);
INSERT   towns  (id,town_name,province_id)               VALUES (501, 'ALTINEKİN', 42);
INSERT   towns  (id,town_name,province_id)               VALUES (502, 'DEREBUCAK', 42);
INSERT   towns  (id,town_name,province_id)               VALUES (503, 'HÜYÜK', 42);
INSERT   towns  (id,town_name,province_id)               VALUES (504, 'KARATAY', 42);
INSERT   towns  (id,town_name,province_id)               VALUES (505, 'MERAM', 42);
INSERT   towns  (id,town_name,province_id)               VALUES (506, 'SELÇUKLU', 42);
INSERT   towns  (id,town_name,province_id)               VALUES (507, 'TAŞKENT', 42);
INSERT   towns  (id,town_name,province_id)               VALUES (508, 'AHIRLI', 42);
INSERT   towns  (id,town_name,province_id)               VALUES (509, 'ÇELTİK', 42);
INSERT   towns  (id,town_name,province_id)               VALUES (510, 'DERBENT', 42);
INSERT   towns  (id,town_name,province_id)               VALUES (511, 'EMİRGAZİ', 42);
INSERT   towns  (id,town_name,province_id)               VALUES (512, 'GÜNEYSINIR', 42);
INSERT   towns  (id,town_name,province_id)               VALUES (513, 'HALKAPINAR', 42);
INSERT   towns  (id,town_name,province_id)               VALUES (514, 'TUZLUKÇU', 42);
INSERT   towns  (id,town_name,province_id)               VALUES (515, 'YALIHÜYÜK', 42);
INSERT   towns  (id,town_name,province_id)               VALUES (516, 'KÜTAHYA  MERKEZ', 43);
INSERT   towns  (id,town_name,province_id)               VALUES (517, 'ALTINTAŞ', 43);
INSERT   towns  (id,town_name,province_id)               VALUES (518, 'DOMANİÇ', 43);
INSERT   towns  (id,town_name,province_id)               VALUES (519, 'EMET', 43);
INSERT   towns  (id,town_name,province_id)               VALUES (520, 'GEDİZ', 43);
INSERT   towns  (id,town_name,province_id)               VALUES (521, 'SİMAV', 43);
INSERT   towns  (id,town_name,province_id)               VALUES (522, 'TAVŞANLI', 43);
INSERT   towns  (id,town_name,province_id)               VALUES (523, 'ASLANAPA', 43);
INSERT   towns  (id,town_name,province_id)               VALUES (524, 'DUMLUPINAR', 43);
INSERT   towns  (id,town_name,province_id)               VALUES (525, 'HİSARCIK', 43);
INSERT   towns  (id,town_name,province_id)               VALUES (526, 'ŞAPHANE', 43);
INSERT   towns  (id,town_name,province_id)               VALUES (527, 'ÇAVDARHİSAR', 43);
INSERT   towns  (id,town_name,province_id)               VALUES (528, 'PAZARLAR', 43);
INSERT   towns  (id,town_name,province_id)               VALUES (529, 'KİLİS MERKEZ', 79);
INSERT   towns  (id,town_name,province_id)               VALUES (530, 'ELBEYLİ', 79);
INSERT   towns  (id,town_name,province_id)               VALUES (531, 'MUSABEYLİ', 79);
INSERT   towns  (id,town_name,province_id)               VALUES (532, 'POLATELİ', 79);
INSERT   towns  (id,town_name,province_id)               VALUES (533, 'MALATYA MERKEZ', 44);
INSERT   towns  (id,town_name,province_id)               VALUES (534, 'AKÇADAĞ', 44);
INSERT   towns  (id,town_name,province_id)               VALUES (535, 'ARAPGİR', 44);
INSERT   towns  (id,town_name,province_id)               VALUES (536, 'ARGUVAN', 44);
INSERT   towns  (id,town_name,province_id)               VALUES (537, 'DARENDE', 44);
INSERT   towns  (id,town_name,province_id)               VALUES (538, 'DOĞANŞEHİR', 44);
INSERT   towns  (id,town_name,province_id)               VALUES (539, 'HEKİMHAN', 44);
INSERT   towns  (id,town_name,province_id)               VALUES (540, 'PÜTÜRGE', 44);
INSERT   towns  (id,town_name,province_id)               VALUES (541, 'YEŞİLYURT', 44);
INSERT   towns  (id,town_name,province_id)               VALUES (542, 'BATTALGAZİ', 44);
INSERT   towns  (id,town_name,province_id)               VALUES (543, 'DOĞANYOL', 44);
INSERT   towns  (id,town_name,province_id)               VALUES (544, 'KALE', 44);
INSERT   towns  (id,town_name,province_id)               VALUES (545, 'KULUNCAK', 44);
INSERT   towns  (id,town_name,province_id)               VALUES (546, 'YAZIHAN', 44);
INSERT   towns  (id,town_name,province_id)               VALUES (547, 'AKHİSAR', 45);
INSERT   towns  (id,town_name,province_id)               VALUES (548, 'ALAŞEHİR', 45);
INSERT   towns  (id,town_name,province_id)               VALUES (549, 'DEMİRCİ', 45);
INSERT   towns  (id,town_name,province_id)               VALUES (550, 'GÖRDES', 45);
INSERT   towns  (id,town_name,province_id)               VALUES (551, 'KIRKAĞAÇ', 45);
INSERT   towns  (id,town_name,province_id)               VALUES (552, 'KULA', 45);
INSERT   towns  (id,town_name,province_id)               VALUES (553, 'MANİSA MERKEZ', 45);
INSERT   towns  (id,town_name,province_id)               VALUES (554, 'SALİHLİ', 45);
INSERT   towns  (id,town_name,province_id)               VALUES (555, 'SARIGÖL', 45);
INSERT   towns  (id,town_name,province_id)               VALUES (556, 'SARUHANLI', 45);
INSERT   towns  (id,town_name,province_id)               VALUES (557, 'SELENDİ', 45);
INSERT   towns  (id,town_name,province_id)               VALUES (558, 'SOMA', 45);
INSERT   towns  (id,town_name,province_id)               VALUES (559, 'TURGUTLU', 45);
INSERT   towns  (id,town_name,province_id)               VALUES (560, 'AHMETLİ', 45);
INSERT   towns  (id,town_name,province_id)               VALUES (561, 'GÖLMARMARA', 45);
INSERT   towns  (id,town_name,province_id)               VALUES (562, 'KÖPRÜBAŞI', 45);
INSERT   towns  (id,town_name,province_id)               VALUES (563, 'DERİK', 47);
INSERT   towns  (id,town_name,province_id)               VALUES (564, 'KIZILTEPE', 47);
INSERT   towns  (id,town_name,province_id)               VALUES (565, 'MARDİN MERKEZ', 47);
INSERT   towns  (id,town_name,province_id)               VALUES (566, 'MAZIDAĞI', 47);
INSERT   towns  (id,town_name,province_id)               VALUES (567, 'MİDYAT', 47);
INSERT   towns  (id,town_name,province_id)               VALUES (568, 'NUSAYBİN', 47);
INSERT   towns  (id,town_name,province_id)               VALUES (569, 'ÖMERLİ', 47);
INSERT   towns  (id,town_name,province_id)               VALUES (570, 'SAVUR', 47);
INSERT   towns  (id,town_name,province_id)               VALUES (571, 'YEŞİLLİ', 47);
INSERT   towns  (id,town_name,province_id)               VALUES (572, 'MERSİN MERKEZ', 33);
INSERT   towns  (id,town_name,province_id)               VALUES (573, 'ANAMUR', 33);
INSERT   towns  (id,town_name,province_id)               VALUES (574, 'ERDEMLİ', 33);
INSERT   towns  (id,town_name,province_id)               VALUES (575, 'GÜLNAR', 33);
INSERT   towns  (id,town_name,province_id)               VALUES (576, 'MUT', 33);
INSERT   towns  (id,town_name,province_id)               VALUES (577, 'SİLİFKE', 33);
INSERT   towns  (id,town_name,province_id)               VALUES (578, 'TARSUS', 33);
INSERT   towns  (id,town_name,province_id)               VALUES (579, 'AYDINCIK', 33);
INSERT   towns  (id,town_name,province_id)               VALUES (580, 'BOZYAZI', 33);
INSERT   towns  (id,town_name,province_id)               VALUES (581, 'ÇAMLIYAYLA', 33);
INSERT   towns  (id,town_name,province_id)               VALUES (582, 'BODRUM', 48);
INSERT   towns  (id,town_name,province_id)               VALUES (583, 'DATÇA', 48);
INSERT   towns  (id,town_name,province_id)               VALUES (584, 'FETHİYE', 48);
INSERT   towns  (id,town_name,province_id)               VALUES (585, 'KÖYCEĞİZ', 48);
INSERT   towns  (id,town_name,province_id)               VALUES (586, 'MARMARİS', 48);
INSERT   towns  (id,town_name,province_id)               VALUES (587, 'MİLAS', 48);
INSERT   towns  (id,town_name,province_id)               VALUES (588, 'MUĞLA MERKEZ', 48);
INSERT   towns  (id,town_name,province_id)               VALUES (589, 'ULA', 48);
INSERT   towns  (id,town_name,province_id)               VALUES (590, 'YATAĞAN', 48);
INSERT   towns  (id,town_name,province_id)               VALUES (591, 'DALAMAN', 48);
INSERT   towns  (id,town_name,province_id)               VALUES (592, 'KAVAKLI DERE', 48);
INSERT   towns  (id,town_name,province_id)               VALUES (593, 'ORTACA', 48);
INSERT   towns  (id,town_name,province_id)               VALUES (594, 'BULANIK', 49);
INSERT   towns  (id,town_name,province_id)               VALUES (595, 'MALAZGİRT', 49);
INSERT   towns  (id,town_name,province_id)               VALUES (596, 'MUŞ MERKEZ', 49);
INSERT   towns  (id,town_name,province_id)               VALUES (597, 'VARTO', 49);
INSERT   towns  (id,town_name,province_id)               VALUES (598, 'HASKÖY', 49);
INSERT   towns  (id,town_name,province_id)               VALUES (599, 'KORKUT', 49);
INSERT   towns  (id,town_name,province_id)               VALUES (600, 'NEVŞEHİR MERKEZ', 50);
INSERT   towns  (id,town_name,province_id)               VALUES (601, 'AVANOS', 50);
INSERT   towns  (id,town_name,province_id)               VALUES (602, 'DERİNKUYU', 50);
INSERT   towns  (id,town_name,province_id)               VALUES (603, 'GÜLŞEHİR', 50);
INSERT   towns  (id,town_name,province_id)               VALUES (604, 'HACIBEKTAŞ', 50);
INSERT   towns  (id,town_name,province_id)               VALUES (605, 'KOZAKLI', 50);
INSERT   towns  (id,town_name,province_id)               VALUES (606, 'ÜRGÜP', 50);
INSERT   towns  (id,town_name,province_id)               VALUES (607, 'ACIGÖL', 50);
INSERT   towns  (id,town_name,province_id)               VALUES (608, 'NİĞDE MERKEZ', 51);
INSERT   towns  (id,town_name,province_id)               VALUES (609, 'BOR', 51);
INSERT   towns  (id,town_name,province_id)               VALUES (610, 'ÇAMARDI', 51);
INSERT   towns  (id,town_name,province_id)               VALUES (611, 'ULUKIŞLA', 51);
INSERT   towns  (id,town_name,province_id)               VALUES (612, 'ALTUNHİSAR', 51);
INSERT   towns  (id,town_name,province_id)               VALUES (613, 'ÇİFTLİK', 51);
INSERT   towns  (id,town_name,province_id)               VALUES (614, 'AKKUŞ', 52);
INSERT   towns  (id,town_name,province_id)               VALUES (615, 'AYBASTI', 52);
INSERT   towns  (id,town_name,province_id)               VALUES (616, 'FATSA', 52);
INSERT   towns  (id,town_name,province_id)               VALUES (617, 'GÖLKÖY', 52);
INSERT   towns  (id,town_name,province_id)               VALUES (618, 'KORGAN', 52);
INSERT   towns  (id,town_name,province_id)               VALUES (619, 'KUMRU', 52);
INSERT   towns  (id,town_name,province_id)               VALUES (620, 'MESUDİYE', 52);
INSERT   towns  (id,town_name,province_id)               VALUES (621, 'ORDU MERKEZ', 52);
INSERT   towns  (id,town_name,province_id)               VALUES (622, 'PERŞEMBE', 52);
INSERT   towns  (id,town_name,province_id)               VALUES (623, 'ULUBEY', 52);
INSERT   towns  (id,town_name,province_id)               VALUES (624, 'ÜNYE', 52);
INSERT   towns  (id,town_name,province_id)               VALUES (625, 'GÜLYALI', 52);
INSERT   towns  (id,town_name,province_id)               VALUES (626, 'GÜRGENTEPE', 52);
INSERT   towns  (id,town_name,province_id)               VALUES (627, 'ÇAMAŞ', 52);
INSERT   towns  (id,town_name,province_id)               VALUES (628, 'ÇATALPINAR', 52);
INSERT   towns  (id,town_name,province_id)               VALUES (629, 'ÇAYBAŞI', 52);
INSERT   towns  (id,town_name,province_id)               VALUES (630, 'İKİZCE', 52);
INSERT   towns  (id,town_name,province_id)               VALUES (631, 'KABADÜZ', 52);
INSERT   towns  (id,town_name,province_id)               VALUES (632, 'KABATAŞ', 52);
INSERT   towns  (id,town_name,province_id)               VALUES (633, 'BAHÇE', 80);
INSERT   towns  (id,town_name,province_id)               VALUES (634, 'KADİRLİ', 80);
INSERT   towns  (id,town_name,province_id)               VALUES (635, 'OSMANİYE MERKEZ', 80);
INSERT   towns  (id,town_name,province_id)               VALUES (636, 'DÜZİÇİ', 80);
INSERT   towns  (id,town_name,province_id)               VALUES (637, 'HASANBEYLİ', 80);
INSERT   towns  (id,town_name,province_id)               VALUES (638, 'SUMBAŞ', 80);
INSERT   towns  (id,town_name,province_id)               VALUES (639, 'TOPRAKKALE', 80);
INSERT   towns  (id,town_name,province_id)               VALUES (640, 'RİZE MERKEZ', 53);
INSERT   towns  (id,town_name,province_id)               VALUES (641, 'ARDEŞEN', 53);
INSERT   towns  (id,town_name,province_id)               VALUES (642, 'ÇAMLIHEMŞİN', 53);
INSERT   towns  (id,town_name,province_id)               VALUES (643, 'ÇAYELİ', 53);
INSERT   towns  (id,town_name,province_id)               VALUES (644, 'FINDIKLI', 53);
INSERT   towns  (id,town_name,province_id)               VALUES (645, 'İKİZDERE', 53);
INSERT   towns  (id,town_name,province_id)               VALUES (646, 'KALKANDERE', 53);
INSERT   towns  (id,town_name,province_id)               VALUES (647, 'PAZAR', 53);
INSERT   towns  (id,town_name,province_id)               VALUES (648, 'GÜNEYSU', 53);
INSERT   towns  (id,town_name,province_id)               VALUES (649, 'DEREPAZARI', 53);
INSERT   towns  (id,town_name,province_id)               VALUES (650, 'HEMŞİN', 53);
INSERT   towns  (id,town_name,province_id)               VALUES (651, 'İYİDERE', 53);
INSERT   towns  (id,town_name,province_id)               VALUES (652, 'AKYAZI', 54);
INSERT   towns  (id,town_name,province_id)               VALUES (653, 'GEYVE', 54);
INSERT   towns  (id,town_name,province_id)               VALUES (654, 'HENDEK', 54);
INSERT   towns  (id,town_name,province_id)               VALUES (655, 'KARASU', 54);
INSERT   towns  (id,town_name,province_id)               VALUES (656, 'KAYNARCA', 54);
INSERT   towns  (id,town_name,province_id)               VALUES (657, 'SAKARYA MERKEZ', 54);
INSERT   towns  (id,town_name,province_id)               VALUES (658, 'PAMUKOVA', 54);
INSERT   towns  (id,town_name,province_id)               VALUES (659, 'TARAKLI', 54);
INSERT   towns  (id,town_name,province_id)               VALUES (660, 'FERİZLİ', 54);
INSERT   towns  (id,town_name,province_id)               VALUES (661, 'KARAPÜRÇEK', 54);
INSERT   towns  (id,town_name,province_id)               VALUES (662, 'SÖĞÜTLÜ', 54);
INSERT   towns  (id,town_name,province_id)               VALUES (663, 'ALAÇAM', 55);
INSERT   towns  (id,town_name,province_id)               VALUES (664, 'BAFRA', 55);
INSERT   towns  (id,town_name,province_id)               VALUES (665, 'ÇARŞAMBA', 55);
INSERT   towns  (id,town_name,province_id)               VALUES (666, 'HAVZA', 55);
INSERT   towns  (id,town_name,province_id)               VALUES (667, 'KAVAK', 55);
INSERT   towns  (id,town_name,province_id)               VALUES (668, 'LADİK', 55);
INSERT   towns  (id,town_name,province_id)               VALUES (669, 'SAMSUN MERKEZ', 55);
INSERT   towns  (id,town_name,province_id)               VALUES (670, 'TERME', 55);
INSERT   towns  (id,town_name,province_id)               VALUES (671, 'VEZİRKÖPRÜ', 55);
INSERT   towns  (id,town_name,province_id)               VALUES (672, 'ASARCIK', 55);
INSERT   towns  (id,town_name,province_id)               VALUES (673, 'ONDOKUZMAYIS', 55);
INSERT   towns  (id,town_name,province_id)               VALUES (674, 'SALIPAZARI', 55);
INSERT   towns  (id,town_name,province_id)               VALUES (675, 'TEKKEKÖY', 55);
INSERT   towns  (id,town_name,province_id)               VALUES (676, 'AYVACIK', 55);
INSERT   towns  (id,town_name,province_id)               VALUES (677, 'YAKAKENT', 55);
INSERT   towns  (id,town_name,province_id)               VALUES (678, 'AYANCIK', 57);
INSERT   towns  (id,town_name,province_id)               VALUES (679, 'BOYABAT', 57);
INSERT   towns  (id,town_name,province_id)               VALUES (680, 'SİNOP MERKEZ', 57);
INSERT   towns  (id,town_name,province_id)               VALUES (681, 'DURAĞAN', 57);
INSERT   towns  (id,town_name,province_id)               VALUES (682, 'ERGELEK', 57);
INSERT   towns  (id,town_name,province_id)               VALUES (683, 'GERZE', 57);
INSERT   towns  (id,town_name,province_id)               VALUES (684, 'TÜRKELİ', 57);
INSERT   towns  (id,town_name,province_id)               VALUES (685, 'DİKMEN', 57);
INSERT   towns  (id,town_name,province_id)               VALUES (686, 'SARAYDÜZÜ', 57);
INSERT   towns  (id,town_name,province_id)               VALUES (687, 'DİVRİĞİ', 58);
INSERT   towns  (id,town_name,province_id)               VALUES (688, 'GEMEREK', 58);
INSERT   towns  (id,town_name,province_id)               VALUES (689, 'GÜRÜN', 58);
INSERT   towns  (id,town_name,province_id)               VALUES (690, 'HAFİK', 58);
INSERT   towns  (id,town_name,province_id)               VALUES (691, 'İMRANLI', 58);
INSERT   towns  (id,town_name,province_id)               VALUES (692, 'KANGAL', 58);
INSERT   towns  (id,town_name,province_id)               VALUES (693, 'KOYUL HİSAR', 58);
INSERT   towns  (id,town_name,province_id)               VALUES (694, 'SİVAS MERKEZ', 58);
INSERT   towns  (id,town_name,province_id)               VALUES (695, 'SU ŞEHRİ', 58);
INSERT   towns  (id,town_name,province_id)               VALUES (696, 'ŞARKIŞLA', 58);
INSERT   towns  (id,town_name,province_id)               VALUES (697, 'YILDIZELİ', 58);
INSERT   towns  (id,town_name,province_id)               VALUES (698, 'ZARA', 58);
INSERT   towns  (id,town_name,province_id)               VALUES (699, 'AKINCILAR', 58);
INSERT   towns  (id,town_name,province_id)               VALUES (700, 'ALTINYAYLA', 58);
INSERT   towns  (id,town_name,province_id)               VALUES (701, 'DOĞANŞAR', 58);
INSERT   towns  (id,town_name,province_id)               VALUES (702, 'GÜLOVA', 58);
INSERT   towns  (id,town_name,province_id)               VALUES (703, 'ULAŞ', 58);
INSERT   towns  (id,town_name,province_id)               VALUES (704, 'BAYKAN', 56);
INSERT   towns  (id,town_name,province_id)               VALUES (705, 'ERUH', 56);
INSERT   towns  (id,town_name,province_id)               VALUES (706, 'KURTALAN', 56);
INSERT   towns  (id,town_name,province_id)               VALUES (707, 'PERVARİ', 56);
INSERT   towns  (id,town_name,province_id)               VALUES (708, 'SİİRT MERKEZ', 56);
INSERT   towns  (id,town_name,province_id)               VALUES (709, 'ŞİRVARİ', 56);
INSERT   towns  (id,town_name,province_id)               VALUES (710, 'AYDINLAR', 56);
INSERT   towns  (id,town_name,province_id)               VALUES (711, 'TEKİRDAĞ MERKEZ', 59);
INSERT   towns  (id,town_name,province_id)               VALUES (712, 'ÇERKEZKÖY', 59);
INSERT   towns  (id,town_name,province_id)               VALUES (713, 'ÇORLU', 59);
INSERT   towns  (id,town_name,province_id)               VALUES (714, 'HAYRABOLU', 59);
INSERT   towns  (id,town_name,province_id)               VALUES (715, 'MALKARA', 59);
INSERT   towns  (id,town_name,province_id)               VALUES (716, 'MURATLI', 59);
INSERT   towns  (id,town_name,province_id)               VALUES (717, 'SARAY', 59);
INSERT   towns  (id,town_name,province_id)               VALUES (718, 'ŞARKÖY', 59);
INSERT   towns  (id,town_name,province_id)               VALUES (719, 'MARAMARAEREĞLİSİ', 59);
INSERT   towns  (id,town_name,province_id)               VALUES (720, 'ALMUS', 60);
INSERT   towns  (id,town_name,province_id)               VALUES (721, 'ARTOVA', 60);
INSERT   towns  (id,town_name,province_id)               VALUES (722, 'TOKAT MERKEZ', 60);
INSERT   towns  (id,town_name,province_id)               VALUES (723, 'ERBAA', 60);
INSERT   towns  (id,town_name,province_id)               VALUES (724, 'NİKSAR', 60);
INSERT   towns  (id,town_name,province_id)               VALUES (725, 'REŞADİYE', 60);
INSERT   towns  (id,town_name,province_id)               VALUES (726, 'TURHAL', 60);
INSERT   towns  (id,town_name,province_id)               VALUES (727, 'ZİLE', 60);
INSERT   towns  (id,town_name,province_id)               VALUES (728, 'PAZAR', 60);
INSERT   towns  (id,town_name,province_id)               VALUES (729, 'YEŞİLYURT', 60);
INSERT   towns  (id,town_name,province_id)               VALUES (730, 'BAŞÇİFTLİK', 60);
INSERT   towns  (id,town_name,province_id)               VALUES (731, 'SULUSARAY', 60);
INSERT   towns  (id,town_name,province_id)               VALUES (732, 'TRABZON MERKEZ', 61);
INSERT   towns  (id,town_name,province_id)               VALUES (733, 'AKÇAABAT', 61);
INSERT   towns  (id,town_name,province_id)               VALUES (734, 'ARAKLI', 61);
INSERT   towns  (id,town_name,province_id)               VALUES (735, 'ARŞİN', 61);
INSERT   towns  (id,town_name,province_id)               VALUES (736, 'ÇAYKARA', 61);
INSERT   towns  (id,town_name,province_id)               VALUES (737, 'MAÇKA', 61);
INSERT   towns  (id,town_name,province_id)               VALUES (738, 'OF', 61);
INSERT   towns  (id,town_name,province_id)               VALUES (739, 'SÜRMENE', 61);
INSERT   towns  (id,town_name,province_id)               VALUES (740, 'TONYA', 61);
INSERT   towns  (id,town_name,province_id)               VALUES (741, 'VAKFIKEBİR', 61);
INSERT   towns  (id,town_name,province_id)               VALUES (742, 'YOMRA', 61);
INSERT   towns  (id,town_name,province_id)               VALUES (743, 'BEŞİKDÜZÜ', 61);
INSERT   towns  (id,town_name,province_id)               VALUES (744, 'ŞALPAZARI', 61);
INSERT   towns  (id,town_name,province_id)               VALUES (745, 'ÇARŞIBAŞI', 61);
INSERT   towns  (id,town_name,province_id)               VALUES (746, 'DERNEKPAZARI', 61);
INSERT   towns  (id,town_name,province_id)               VALUES (747, 'DÜZKÖY', 61);
INSERT   towns  (id,town_name,province_id)               VALUES (748, 'HAYRAT', 61);
INSERT   towns  (id,town_name,province_id)               VALUES (749, 'KÖPRÜBAŞI', 61);
INSERT   towns  (id,town_name,province_id)               VALUES (750, 'TUNCELİ MERKEZ', 62);
INSERT   towns  (id,town_name,province_id)               VALUES (751, 'ÇEMİŞGEZEK', 62);
INSERT   towns  (id,town_name,province_id)               VALUES (752, 'HOZAT', 62);
INSERT   towns  (id,town_name,province_id)               VALUES (753, 'MAZGİRT', 62);
INSERT   towns  (id,town_name,province_id)               VALUES (754, 'NAZİMİYE', 62);
INSERT   towns  (id,town_name,province_id)               VALUES (755, 'OVACIK', 62);
INSERT   towns  (id,town_name,province_id)               VALUES (756, 'PERTEK', 62);
INSERT   towns  (id,town_name,province_id)               VALUES (757, 'PÜLÜMÜR', 62);
INSERT   towns  (id,town_name,province_id)               VALUES (758, 'BANAZ', 64);
INSERT   towns  (id,town_name,province_id)               VALUES (759, 'EŞME', 64);
INSERT   towns  (id,town_name,province_id)               VALUES (760, 'KARAHALLI', 64);
INSERT   towns  (id,town_name,province_id)               VALUES (761, 'SİVASLI', 64);
INSERT   towns  (id,town_name,province_id)               VALUES (762, 'ULUBEY', 64);
INSERT   towns  (id,town_name,province_id)               VALUES (763, 'UŞAK MERKEZ', 64);
INSERT   towns  (id,town_name,province_id)               VALUES (764, 'BAŞKALE', 65);
INSERT   towns  (id,town_name,province_id)               VALUES (765, 'VAN MERKEZ', 65);
INSERT   towns  (id,town_name,province_id)               VALUES (766, 'EDREMİT', 65);
INSERT   towns  (id,town_name,province_id)               VALUES (767, 'ÇATAK', 65);
INSERT   towns  (id,town_name,province_id)               VALUES (768, 'ERCİŞ', 65);
INSERT   towns  (id,town_name,province_id)               VALUES (769, 'GEVAŞ', 65);
INSERT   towns  (id,town_name,province_id)               VALUES (770, 'GÜRPINAR', 65);
INSERT   towns  (id,town_name,province_id)               VALUES (771, 'MURADİYE', 65);
INSERT   towns  (id,town_name,province_id)               VALUES (772, 'ÖZALP', 65);
INSERT   towns  (id,town_name,province_id)               VALUES (773, 'BAHÇESARAY', 65);
INSERT   towns  (id,town_name,province_id)               VALUES (774, 'ÇALDIRAN', 65);
INSERT   towns  (id,town_name,province_id)               VALUES (775, 'SARAY', 65);
INSERT   towns  (id,town_name,province_id)               VALUES (776, 'YALOVA MERKEZ', 77);
INSERT   towns  (id,town_name,province_id)               VALUES (777, 'ALTINOVA', 77);
INSERT   towns  (id,town_name,province_id)               VALUES (778, 'ARMUTLU', 77);
INSERT   towns  (id,town_name,province_id)               VALUES (779, 'ÇINARCIK', 77);
INSERT   towns  (id,town_name,province_id)               VALUES (780, 'ÇİFTLİKKÖY', 77);
INSERT   towns  (id,town_name,province_id)               VALUES (781, 'TERMAL', 77);
INSERT   towns  (id,town_name,province_id)               VALUES (782, 'AKDAĞMADENİ', 66);
INSERT   towns  (id,town_name,province_id)               VALUES (783, 'BOĞAZLIYAN', 66);
INSERT   towns  (id,town_name,province_id)               VALUES (784, 'YOZGAT MERKEZ', 66);
INSERT   towns  (id,town_name,province_id)               VALUES (785, 'ÇAYIRALAN', 66);
INSERT   towns  (id,town_name,province_id)               VALUES (786, 'ÇEKEREK', 66);
INSERT   towns  (id,town_name,province_id)               VALUES (787, 'SARIKAYA', 66);
INSERT   towns  (id,town_name,province_id)               VALUES (788, 'SORGUN', 66);
INSERT   towns  (id,town_name,province_id)               VALUES (789, 'ŞEFAATLI', 66);
INSERT   towns  (id,town_name,province_id)               VALUES (790, 'YERKÖY', 66);
INSERT   towns  (id,town_name,province_id)               VALUES (791, 'KADIŞEHRİ', 66);
INSERT   towns  (id,town_name,province_id)               VALUES (792, 'SARAYKENT', 66);
INSERT   towns  (id,town_name,province_id)               VALUES (793, 'YENİFAKILI', 66);
INSERT   towns  (id,town_name,province_id)               VALUES (794, 'ÇAYCUMA', 67);
INSERT   towns  (id,town_name,province_id)               VALUES (795, 'DEVREK', 67);
INSERT   towns  (id,town_name,province_id)               VALUES (796, 'ZONGULDAK MERKEZ', 67);
INSERT   towns  (id,town_name,province_id)               VALUES (797, 'EREĞLİ', 67);
INSERT   towns  (id,town_name,province_id)               VALUES (798, 'ALAPLI', 67);
INSERT   towns  (id,town_name,province_id)               VALUES (799, 'GÖKÇEBEY', 67);
INSERT   towns  (id,town_name,province_id)               VALUES (800, 'ÇANAKKALE MERKEZ', 17);
INSERT   towns  (id,town_name,province_id)               VALUES (801, 'AYVACIK', 17);
INSERT   towns  (id,town_name,province_id)               VALUES (802, 'BAYRAMİÇ', 17);
INSERT   towns  (id,town_name,province_id)               VALUES (803, 'BİGA', 17);
INSERT   towns  (id,town_name,province_id)               VALUES (804, 'BOZCAADA', 17);
INSERT   towns  (id,town_name,province_id)               VALUES (805, 'ÇAN', 17);
INSERT   towns  (id,town_name,province_id)               VALUES (806, 'ECEABAT', 17);
INSERT   towns  (id,town_name,province_id)               VALUES (807, 'EZİNE', 17);
INSERT   towns  (id,town_name,province_id)               VALUES (808, 'LAPSEKİ', 17);
INSERT   towns  (id,town_name,province_id)               VALUES (809, 'YENİCE', 17);
INSERT   towns  (id,town_name,province_id)               VALUES (810, 'ÇANKIRI MERKEZ', 18);
INSERT   towns  (id,town_name,province_id)               VALUES (811, 'ÇERKEŞ', 18);
INSERT   towns  (id,town_name,province_id)               VALUES (812, 'ELDİVAN', 18);
INSERT   towns  (id,town_name,province_id)               VALUES (813, 'ILGAZ', 18);
INSERT   towns  (id,town_name,province_id)               VALUES (814, 'KURŞUNLU', 18);
INSERT   towns  (id,town_name,province_id)               VALUES (815, 'ORTA', 18);
INSERT   towns  (id,town_name,province_id)               VALUES (816, 'ŞABANÖZÜ', 18);
INSERT   towns  (id,town_name,province_id)               VALUES (817, 'YAPRAKLI', 18);
INSERT   towns  (id,town_name,province_id)               VALUES (818, 'ATKARACALAR', 18);
INSERT   towns  (id,town_name,province_id)               VALUES (819, 'KIZILIRMAK', 18);
INSERT   towns  (id,town_name,province_id)               VALUES (820, 'BAYRAMÖREN', 18);
INSERT   towns  (id,town_name,province_id)               VALUES (821, 'KORGUN', 18);
INSERT   towns  (id,town_name,province_id)               VALUES (822, 'ALACA', 19);
INSERT   towns  (id,town_name,province_id)               VALUES (823, 'BAYAT', 19);
INSERT   towns  (id,town_name,province_id)               VALUES (824, 'ÇORUM MERKEZ', 19);
INSERT   towns  (id,town_name,province_id)               VALUES (825, 'İKSİPLİ', 19);
INSERT   towns  (id,town_name,province_id)               VALUES (826, 'KARGI', 19);
INSERT   towns  (id,town_name,province_id)               VALUES (827, 'MECİTÖZÜ', 19);
INSERT   towns  (id,town_name,province_id)               VALUES (828, 'ORTAKÖY', 19);
INSERT   towns  (id,town_name,province_id)               VALUES (829, 'OSMANCIK', 19);
INSERT   towns  (id,town_name,province_id)               VALUES (830, 'SUNGURLU', 19);
INSERT   towns  (id,town_name,province_id)               VALUES (831, 'DODURGA', 19);
INSERT   towns  (id,town_name,province_id)               VALUES (832, 'LAÇİN', 19);
INSERT   towns  (id,town_name,province_id)               VALUES (833, 'OĞUZLAR', 19);
INSERT   towns  (id,town_name,province_id)               VALUES (834, 'ADALAR', 34);
INSERT   towns  (id,town_name,province_id)               VALUES (835, 'BAKIRKÖY', 34);
INSERT   towns  (id,town_name,province_id)               VALUES (836, 'BEŞİKTAŞ', 34);
INSERT   towns  (id,town_name,province_id)               VALUES (837, 'BEYKOZ', 34);
INSERT   towns  (id,town_name,province_id)               VALUES (838, 'BEYOĞLU', 34);
INSERT   towns  (id,town_name,province_id)               VALUES (839, 'ÇATALCA', 34);
INSERT   towns  (id,town_name,province_id)               VALUES (840, 'EMİNÖNÜ', 34);
INSERT   towns  (id,town_name,province_id)               VALUES (841, 'EYÜP', 34);
INSERT   towns  (id,town_name,province_id)               VALUES (842, 'FATİH', 34);
INSERT   towns  (id,town_name,province_id)               VALUES (843, 'GAZİOSMANPAŞA', 34);
INSERT   towns  (id,town_name,province_id)               VALUES (844, 'KADIKÖY', 34);
INSERT   towns  (id,town_name,province_id)               VALUES (845, 'KARTAL', 34);
INSERT   towns  (id,town_name,province_id)               VALUES (846, 'SARIYER', 34);
INSERT   towns  (id,town_name,province_id)               VALUES (847, 'SİLİVRİ', 34);
INSERT   towns  (id,town_name,province_id)               VALUES (848, 'ŞİLE', 34);
INSERT   towns  (id,town_name,province_id)               VALUES (849, 'ŞİŞLİ', 34);
INSERT   towns  (id,town_name,province_id)               VALUES (850, 'ÜSKÜDAR', 34);
INSERT   towns  (id,town_name,province_id)               VALUES (851, 'ZEYTİNBURNU', 34);
INSERT   towns  (id,town_name,province_id)               VALUES (852, 'BÜYÜKÇEKMECE', 34);
INSERT   towns  (id,town_name,province_id)               VALUES (853, 'KAĞITHANE', 34);
INSERT   towns  (id,town_name,province_id)               VALUES (854, 'KÜÇÜKÇEKMECE', 34);
INSERT   towns  (id,town_name,province_id)               VALUES (855, 'PENDİK', 34);
INSERT   towns  (id,town_name,province_id)               VALUES (856, 'ÜMRANİYE', 34);
INSERT   towns  (id,town_name,province_id)               VALUES (857, 'BAYRAMPAŞA', 34);
INSERT   towns  (id,town_name,province_id)               VALUES (858, 'AVCILAR', 34);
INSERT   towns  (id,town_name,province_id)               VALUES (859, 'BAĞCILAR', 34);
INSERT   towns  (id,town_name,province_id)               VALUES (860, 'BAHÇELİEVLER', 34);
INSERT   towns  (id,town_name,province_id)               VALUES (861, 'GÜNGÖREN', 34);
INSERT   towns  (id,town_name,province_id)               VALUES (862, 'MALTEPE', 34);
INSERT   towns  (id,town_name,province_id)               VALUES (863, 'SULTANBEYLİ', 34);
INSERT   towns  (id,town_name,province_id)               VALUES (864, 'TUZLA', 34);
INSERT   towns  (id,town_name,province_id)               VALUES (865, 'ESENLER', 34);
INSERT   towns  (id,town_name,province_id)               VALUES (866, 'ALİAĞA', 35);
INSERT   towns  (id,town_name,province_id)               VALUES (867, 'BAYINDIR', 35);
INSERT   towns  (id,town_name,province_id)               VALUES (868, 'BERGAMA', 35);
INSERT   towns  (id,town_name,province_id)               VALUES (869, 'BORNOVA', 35);
INSERT   towns  (id,town_name,province_id)               VALUES (870, 'ÇEŞME', 35);
INSERT   towns  (id,town_name,province_id)               VALUES (871, 'DİKİLİ', 35);
INSERT   towns  (id,town_name,province_id)               VALUES (872, 'FOÇA', 35);
INSERT   towns  (id,town_name,province_id)               VALUES (873, 'KARABURUN', 35);
INSERT   towns  (id,town_name,province_id)               VALUES (874, 'KARŞIYAKA', 35);
INSERT   towns  (id,town_name,province_id)               VALUES (875, 'KEMALPAŞA', 35);
INSERT   towns  (id,town_name,province_id)               VALUES (876, 'KINIK', 35);
INSERT   towns  (id,town_name,province_id)               VALUES (877, 'KİRAZ', 35);
INSERT   towns  (id,town_name,province_id)               VALUES (878, 'MENEMEN', 35);
INSERT   towns  (id,town_name,province_id)               VALUES (879, 'ÖDEMİŞ', 35);
INSERT   towns  (id,town_name,province_id)               VALUES (880, 'SEFERİHİSAR', 35);
INSERT   towns  (id,town_name,province_id)               VALUES (881, 'SELÇUK', 35);
INSERT   towns  (id,town_name,province_id)               VALUES (882, 'TİRE', 35);
INSERT   towns  (id,town_name,province_id)               VALUES (883, 'TORBALI', 35);
INSERT   towns  (id,town_name,province_id)               VALUES (884, 'URLA', 35);
INSERT   towns  (id,town_name,province_id)               VALUES (885, 'BEYDAĞ', 35);
INSERT   towns  (id,town_name,province_id)               VALUES (886, 'BUCA', 35);
INSERT   towns  (id,town_name,province_id)               VALUES (887, 'KONAK', 35);
INSERT   towns  (id,town_name,province_id)               VALUES (888, 'MENDERES', 35);
INSERT   towns  (id,town_name,province_id)               VALUES (889, 'BALÇOVA', 35);
INSERT   towns  (id,town_name,province_id)               VALUES (890, 'ÇİGLİ', 35);
INSERT   towns  (id,town_name,province_id)               VALUES (891, 'GAZİEMİR', 35);
INSERT   towns  (id,town_name,province_id)               VALUES (892, 'NARLIDERE', 35);
INSERT   towns  (id,town_name,province_id)               VALUES (893, 'GÜZELBAHÇE', 35);
INSERT   towns  (id,town_name,province_id)               VALUES (894, 'ŞANLIURFA MERKEZ', 63);
INSERT   towns  (id,town_name,province_id)               VALUES (895, 'AKÇAKALE', 63);
INSERT   towns  (id,town_name,province_id)               VALUES (896, 'BİRECİK', 63);
INSERT   towns  (id,town_name,province_id)               VALUES (897, 'BOZOVA', 63);
INSERT   towns  (id,town_name,province_id)               VALUES (898, 'CEYLANPINAR', 63);
INSERT   towns  (id,town_name,province_id)               VALUES (899, 'HALFETİ', 63);
INSERT   towns  (id,town_name,province_id)               VALUES (900, 'HİLVAN', 63);
INSERT   towns  (id,town_name,province_id)               VALUES (901, 'SİVEREK', 63);
INSERT   towns  (id,town_name,province_id)               VALUES (902, 'SURUÇ', 63);
INSERT   towns  (id,town_name,province_id)               VALUES (903, 'VİRANŞEHİR', 63);
INSERT   towns  (id,town_name,province_id)               VALUES (904, 'HARRAN', 63);
INSERT   towns  (id,town_name,province_id)               VALUES (905, 'BEYTÜŞŞEBAP', 73);
INSERT   towns  (id,town_name,province_id)               VALUES (906, 'ŞIRNAK MERKEZ', 73);
INSERT   towns  (id,town_name,province_id)               VALUES (907, 'CİZRE', 73);
INSERT   towns  (id,town_name,province_id)               VALUES (908, 'İDİL', 73);
INSERT   towns  (id,town_name,province_id)               VALUES (909, 'SİLOPİ', 73);
INSERT   towns  (id,town_name,province_id)               VALUES (910, 'ULUDERE', 73);
INSERT   towns  (id,town_name,province_id)               VALUES (911, 'GÜÇLÜKONAK', 73);

























