use  mydatabase;

create table cities(
int primary key city_id,
varchar (300) city_name
)



INSERT cities (id, city_name) VALUES (1, 'ADANA');
INSERT cities (id, city_name) VALUES (2, 'ADIYAMA');
INSERT cities (id, city_name) VALUES (3, 'AFYO');
INSERT cities (id, city_name) VALUES (4, 'AĞRI');
INSERT cities (id, city_name) VALUES (5, 'AMASYA');
INSERT cities (id, city_name) VALUES (6, 'ANKARA');
INSERT cities (id, city_name) VALUES (7, 'ANTALYA');
INSERT cities (id, city_name) VALUES (8, 'ARTVİ');
INSERT cities (id, city_name) VALUES (9, 'AYDI');
INSERT cities (id, city_name) VALUES (10, 'BALIKESİR');
INSERT cities (id, city_name) VALUES (11, 'BİLECİK');
INSERT cities (id, city_name) VALUES (12, 'BİNGÖL');
INSERT cities (id, city_name) VALUES (13, 'BİTLİS');
INSERT cities (id, city_name) VALUES (14, 'BOLU');
INSERT cities (id, city_name) VALUES (15, 'BURDUR');
INSERT cities (id, city_name) VALUES (16, 'BURSA');
INSERT cities (id, city_name) VALUES (17, 'ÇANAKKALE');
INSERT cities (id, city_name) VALUES (18, 'ÇANKIRI');
INSERT cities (id, city_name) VALUES (19, 'ÇORUM');
INSERT cities (id, city_name) VALUES (20, 'DENİZLİ');
INSERT cities (id, city_name) VALUES (21, 'DİYARBAKIR');
INSERT cities (id, city_name) VALUES (22, 'EDİRNE');
INSERT cities (id, city_name) VALUES (23, 'ELAZIĞ');
INSERT cities (id, city_name) VALUES (24, 'ERZİNCA');
INSERT cities (id, city_name) VALUES (25, 'ERZURUM');
INSERT cities (id, city_name) VALUES (26, 'ESKİŞEHİR');
INSERT cities (id, city_name) VALUES (27, 'GAZİANTEP');
INSERT cities (id, city_name) VALUES (28, 'GİRESU');
INSERT cities (id, city_name) VALUES (29, 'GÜMÜŞHANE');
INSERT cities (id, city_name) VALUES (30, 'HAKKARİ');
INSERT cities (id, city_name) VALUES (31, 'HATAY');
INSERT cities (id, city_name) VALUES (32, 'ISPARTA');
INSERT cities (id, city_name) VALUES (33, 'İÇEL');
INSERT cities (id, city_name) VALUES (34, 'İSTANBUL');
INSERT cities (id, city_name) VALUES (35, 'İZMİR');
INSERT cities (id, city_name) VALUES (36, 'KARS');
INSERT cities (id, city_name) VALUES (37, 'KASTAMONU');
INSERT cities (id, city_name) VALUES (38, 'KAYSERİ');
INSERT cities (id, city_name) VALUES (39, 'KIRKLARELİ');
INSERT cities (id, city_name) VALUES (40, 'KIRŞEHİR');
INSERT cities (id, city_name) VALUES (41, 'KOCAELİ');
INSERT cities (id, city_name) VALUES (42, 'KONYA');
INSERT cities (id, city_name) VALUES (43, 'KÜTAHYA');
INSERT cities (id, city_name) VALUES (44, 'MALATYA');
INSERT cities (id, city_name) VALUES (45, 'MANİSA');
INSERT cities (id, city_name) VALUES (46, 'KAHRAMANMARAŞ');
INSERT cities (id, city_name) VALUES (47, 'MARDİ');
INSERT cities (id, city_name) VALUES (48, 'MUĞLA');
INSERT cities (id, city_name) VALUES (49, 'MUŞ');
INSERT cities (id, city_name) VALUES (50, 'NEVŞEHİR');
INSERT cities (id, city_name) VALUES (51, 'NİĞDE');
INSERT cities (id, city_name) VALUES (52, 'ORDU');
INSERT cities (id, city_name) VALUES (53, 'RİZE');
INSERT cities (id, city_name) VALUES (54, 'SAKARYA');
INSERT cities (id, city_name) VALUES (55, 'SAMSU');
INSERT cities (id, city_name) VALUES (56, 'SİİRT');
INSERT cities (id, city_name) VALUES (57, 'SİNOP');
INSERT cities (id, city_name) VALUES (58, 'SİVAS');
INSERT cities (id, city_name) VALUES (59, 'TEKİRDAĞ');
INSERT cities (id, city_name) VALUES (60, 'TOKAT');
INSERT cities (id, city_name) VALUES (61, 'TRABZO');
INSERT cities (id, city_name) VALUES (62, 'TUNCELİ');
INSERT cities (id, city_name) VALUES (63, 'ŞANLIURFA');
INSERT cities (id, city_name) VALUES (64, 'UŞAK');
INSERT cities (id, city_name) VALUES (65, 'VA');
INSERT cities (id, city_name) VALUES (66, 'YOZGAT');
INSERT cities (id, city_name) VALUES (67, 'ZONGULDAK');
INSERT cities (id, city_name) VALUES (68, 'AKSARAY');
INSERT cities (id, city_name) VALUES (69, 'BAYBURT');
INSERT cities (id, city_name) VALUES (70, 'KARAMA');
INSERT cities (id, city_name) VALUES (71, 'KIRIKKALE');
INSERT cities (id, city_name) VALUES (72, 'BATMA');
INSERT cities (id, city_name) VALUES (73, 'ŞIRNAK');
INSERT cities (id, city_name) VALUES (74, 'BARTI');
INSERT cities (id, city_name) VALUES (75, 'ARDAHA');
INSERT cities (id, city_name) VALUES (76, 'IĞDIR');
INSERT cities (id, city_name) VALUES (77, 'YALOVA');
INSERT cities (id, city_name) VALUES (78, 'KARABÜK');
INSERT cities (id, city_name) VALUES (79, 'KİLİS');
INSERT cities (id, city_name) VALUES (80, 'OSMANİYE');
INSERT cities (id, city_name) VALUES (81, 'DÜZCE');
